name: Weekly Energy Prediction

on:
  schedule:
    # Every Monday 00:00 Jakarta (UTC+7 â†’ Sunday 17:00 UTC)
    - cron: "0 * * * *"

  workflow_dispatch:   # manual trigger (recommended)

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run prediction and push to ThingSpeak
      env:
        THINGSPEAK_CHANNEL_ID: ${{ secrets.THINGSPEAK_CHANNEL_ID }}
        THINGSPEAK_READ_API_KEY: ${{ secrets.THINGSPEAK_READ_API_KEY }}
        THINGSPEAK_WRITE_API_KEY: ${{ secrets.THINGSPEAK_WRITE_API_KEY}}
        THINGSPEAK_WRITE_CHANNEL_ID: ${{ secrets.THINGSPEAK_WRITE_CHANNEL_ID}}
        THINGPSEAK_USER_API_KEY: ${{ secrets.THINGSPEAK_USER_API_KEY}}
      run: |
        python scripts/predict.py
